version: '3.7'
#
services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:2020.4.0.547.0
    init: true
    hostname: iris
    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    - ./UserCPF:/home/irisowner/cpf

    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
